# Generated by Django 4.2 on 2024-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.CharField(default='', max_length=100, verbose_name='value'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
