# Generated by Django 4.2 on 2024-05-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(max_length=100, verbose_name='value'),
        ),
    ]
